# Project
version=1.0.0
group=dev.thomasglasser.multiloadertemplate

# Mod options
mod_name=Multiloader Template
mod_author=Thomas Glasser
mod_id=multiloadertemplate
contributors='Me, idea', 'Myself, code', 'I, art'
description=Template for making multi-loader mods
license=LGPL-3.0
license_url=https://www.gnu.org/licenses/lgpl-3.0-standalone.html
icon=icon.png
github_name=Multiloader-Template
java_version=21

# Common
minecraft_version=1.21.1
previous_minecraft_version=1.21
next_minecraft_version=1.21.2
mdg_version=2.0.80
neoform_version=20240808.144430
mixin_version=0.15.2+mixin.0.8.7
mixinextras_version=0.4.1

# Parchment
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Dependencies
tommylib_version=30.1.1

# Runtime
jade_version=15.10.0
jei_version=19.21.0.247

# NeoForge
neoforge_version=21.1.90
major_fml_version=4

# Fabric
fabric_version=0.110.0+1.21.1
fabric_loader_version=0.16.9
loom_version=1.9.+

# Runtime
modmenu_version=11.0.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
